{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibjev",
    "module": "klibjev",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibjev-metadata-1.0.1-SNAPSHOT.jar",
          "url": "klibjev-1.0.1-SNAPSHOT.jar",
          "size": 11949,
          "sha512": "a5dba05750bb8d6094cf8ed810767f08131a1dc688aef01ab70fbc684eb9ff3f1324130624627e83e342aa1ccdb05d0b1eabf9fc25ac407e5f6cdf5db70cd878",
          "sha256": "122998d511f58bf94b0fe83875b7152375fd693993623ccadb45140ba33bb57e",
          "sha1": "f7c14c797d44fc0050997a50566eb9fa4b71fab3",
          "md5": "5aa05c2acc9947e94719367ab6d637bc"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibjev-kotlin-1.0.1-SNAPSHOT-sources.jar",
          "url": "klibjev-1.0.1-SNAPSHOT-sources.jar",
          "size": 13609,
          "sha512": "8551ec0cb745e407dd48bee8d784e0823fd8796a15841d49bb991085ee0a5ae8da1c60324610e101012980f7fae4069cdd5f741644a6455ae00887ced50d298e",
          "sha256": "cac8d9426db27a58ef2b02887217307daf53572cb6746f133966b534c2ecf4c8",
          "sha1": "cfdbf2b94afd6f81c031ea95f94a90b8eb7af55e",
          "md5": "440d7575e897d8d798d5ebfd857f072c"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibjev-jvm/1.0.1-SNAPSHOT/klibjev-jvm-1.0.1-SNAPSHOT.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-jvm",
        "version": "1.0.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibjev-jvm/1.0.1-SNAPSHOT/klibjev-jvm-1.0.1-SNAPSHOT.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-jvm",
        "version": "1.0.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibjev-jvm/1.0.1-SNAPSHOT/klibjev-jvm-1.0.1-SNAPSHOT.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-jvm",
        "version": "1.0.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibjev-macosarm64/1.0.1-SNAPSHOT/klibjev-macosarm64-1.0.1-SNAPSHOT.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-macosarm64",
        "version": "1.0.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibjev-macosarm64/1.0.1-SNAPSHOT/klibjev-macosarm64-1.0.1-SNAPSHOT.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-macosarm64",
        "version": "1.0.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibjev-macosarm64/1.0.1-SNAPSHOT/klibjev-macosarm64-1.0.1-SNAPSHOT.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-macosarm64",
        "version": "1.0.1-SNAPSHOT"
      }
    }
  ]
}
