{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibjev/1.0.0-SNAPSHOT/klibjev-1.0.0-SNAPSHOT.module",
    "group": "org.jraf.klibjev",
    "module": "klibjev",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibjev-jvm-1.0.0-SNAPSHOT.jar",
          "url": "klibjev-jvm-1.0.0-SNAPSHOT.jar",
          "size": 126314,
          "sha512": "006aefdae42b334a9331557bcaf00804a663df51032b76705d6dcdc383b1fcd79d058167c961c5235dc5295cb7e20f485e3f8b96b1676c58f1796735da4c5eab",
          "sha256": "64f4fbe718423bffee3153e316b59053b4dcacd9c63cd0c759db3d2bc3f11f35",
          "sha1": "b1c9b316f475d506d5eedb4367c6c3c0a169e1d4",
          "md5": "a8c9697b519997877fa340b8f2289c30"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibjev-jvm-1.0.0-SNAPSHOT.jar",
          "url": "klibjev-jvm-1.0.0-SNAPSHOT.jar",
          "size": 126314,
          "sha512": "006aefdae42b334a9331557bcaf00804a663df51032b76705d6dcdc383b1fcd79d058167c961c5235dc5295cb7e20f485e3f8b96b1676c58f1796735da4c5eab",
          "sha256": "64f4fbe718423bffee3153e316b59053b4dcacd9c63cd0c759db3d2bc3f11f35",
          "sha1": "b1c9b316f475d506d5eedb4367c6c3c0a169e1d4",
          "md5": "a8c9697b519997877fa340b8f2289c30"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibjev-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "klibjev-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 13343,
          "sha512": "9597d7fa125bb8a5286d2d3a2f34d51af8e96e14be159bc83bc8e71bc9a4a7eab7e33772b9ede5bd8616576172c4acd2cbd0c3ccdfc1140d54653e3f82fa4c6c",
          "sha256": "a3c3e863a1fbaa132f50700c26d5e960b25eee3b7658da39ad6bed694669f29b",
          "sha1": "7846515f8d3441806cc11d0821c7ffb5f4f5b33d",
          "md5": "4b37676cede9201cd1a510e294238560"
        }
      ]
    }
  ]
}
