{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibjev",
    "module": "klibjev",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibjev-metadata-1.0.0-SNAPSHOT.jar",
          "url": "klibjev-1.0.0-SNAPSHOT.jar",
          "size": 11617,
          "sha512": "0aa3f7a18bac95bff13f2f1825fb849465ed45ada97b0e9d074f3c56535a03ecb6ba14740f5e222bedfc3a2ce3b3f7385ee016b03b9353ab2231ed99da89766f",
          "sha256": "7d11216e7e7fb4c1301ba4899fae3da511faf8b38b22385e2e90bb0ec30f67be",
          "sha1": "1e72c031147081cd28297206c76d19fcf3632766",
          "md5": "f6af07ba6846e5cc520e5515a068d311"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibjev-kotlin-1.0.0-SNAPSHOT-sources.jar",
          "url": "klibjev-1.0.0-SNAPSHOT-sources.jar",
          "size": 13343,
          "sha512": "9597d7fa125bb8a5286d2d3a2f34d51af8e96e14be159bc83bc8e71bc9a4a7eab7e33772b9ede5bd8616576172c4acd2cbd0c3ccdfc1140d54653e3f82fa4c6c",
          "sha256": "a3c3e863a1fbaa132f50700c26d5e960b25eee3b7658da39ad6bed694669f29b",
          "sha1": "7846515f8d3441806cc11d0821c7ffb5f4f5b33d",
          "md5": "4b37676cede9201cd1a510e294238560"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibjev-jvm/1.0.0-SNAPSHOT/klibjev-jvm-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibjev-jvm/1.0.0-SNAPSHOT/klibjev-jvm-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibjev-jvm/1.0.0-SNAPSHOT/klibjev-jvm-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibjev-macosarm64/1.0.0-SNAPSHOT/klibjev-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibjev-macosarm64/1.0.0-SNAPSHOT/klibjev-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibjev-macosarm64/1.0.0-SNAPSHOT/klibjev-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
