{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibjev",
    "module": "klibjev",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibjev-metadata-1.0.0.jar",
          "url": "klibjev-1.0.0.jar",
          "size": 11617,
          "sha512": "0aa3f7a18bac95bff13f2f1825fb849465ed45ada97b0e9d074f3c56535a03ecb6ba14740f5e222bedfc3a2ce3b3f7385ee016b03b9353ab2231ed99da89766f",
          "sha256": "7d11216e7e7fb4c1301ba4899fae3da511faf8b38b22385e2e90bb0ec30f67be",
          "sha1": "1e72c031147081cd28297206c76d19fcf3632766",
          "md5": "f6af07ba6846e5cc520e5515a068d311"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibjev-kotlin-1.0.0-sources.jar",
          "url": "klibjev-1.0.0-sources.jar",
          "size": 13336,
          "sha512": "062eebac79b4a9e816858d39efbc0cc034a5f3b0a4981a66a5bb780a5dbaa5cdd245b1e74a6360b2d25c8ca4b9e566923cf2dd95bee049d07f358b8af5b4eaeb",
          "sha256": "8df422d558c814e4e795f5d8b92b6cc78902d66d0a20fd9ee05c50d92076032e",
          "sha1": "fbe5d85148f8fd5f382e016bfb5d60230ac0631c",
          "md5": "d848ceb0e5aeed92b81a7865f70bda9d"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibjev-jvm/1.0.0/klibjev-jvm-1.0.0.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibjev-jvm/1.0.0/klibjev-jvm-1.0.0.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibjev-jvm/1.0.0/klibjev-jvm-1.0.0.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibjev-macosarm64/1.0.0/klibjev-macosarm64-1.0.0.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-macosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibjev-macosarm64/1.0.0/klibjev-macosarm64-1.0.0.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-macosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibjev-macosarm64/1.0.0/klibjev-macosarm64-1.0.0.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-macosarm64",
        "version": "1.0.0"
      }
    }
  ]
}
