{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibjev",
    "module": "klibjev",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibjev-metadata-1.0.0.jar",
          "url": "klibjev-1.0.0.jar",
          "size": 11949,
          "sha512": "a5dba05750bb8d6094cf8ed810767f08131a1dc688aef01ab70fbc684eb9ff3f1324130624627e83e342aa1ccdb05d0b1eabf9fc25ac407e5f6cdf5db70cd878",
          "sha256": "122998d511f58bf94b0fe83875b7152375fd693993623ccadb45140ba33bb57e",
          "sha1": "f7c14c797d44fc0050997a50566eb9fa4b71fab3",
          "md5": "5aa05c2acc9947e94719367ab6d637bc"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibjev-kotlin-1.0.0-sources.jar",
          "url": "klibjev-1.0.0-sources.jar",
          "size": 13602,
          "sha512": "d03f5c30bedfe539add9f42ef4d9f1445ecac6d5c55b9c2040758947d88f4e001482592f2c892ed54b76b1b90fcd110e8d39a2315bfcd80f6082221dc7591023",
          "sha256": "ed21512479f5513183c778aa76dfb472f328e929e1ce768ef01c3d31c84b0a64",
          "sha1": "249ce46cb97fd3c0a86d5bae2570d3e5c25c7bde",
          "md5": "4591e562e6362242ee4cce1edaf16865"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibjev-jvm/1.0.0/klibjev-jvm-1.0.0.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibjev-jvm/1.0.0/klibjev-jvm-1.0.0.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibjev-jvm/1.0.0/klibjev-jvm-1.0.0.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibjev-macosarm64/1.0.0/klibjev-macosarm64-1.0.0.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-macosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibjev-macosarm64/1.0.0/klibjev-macosarm64-1.0.0.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-macosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibjev-macosarm64/1.0.0/klibjev-macosarm64-1.0.0.module",
        "group": "org.jraf.klibjev",
        "module": "klibjev-macosarm64",
        "version": "1.0.0"
      }
    }
  ]
}
