{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibjev/1.0.0/klibjev-1.0.0.module",
    "group": "org.jraf.klibjev",
    "module": "klibjev",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibjev-jvm-1.0.0.jar",
          "url": "klibjev-jvm-1.0.0.jar",
          "size": 126305,
          "sha512": "a72967427b924d212ce56af8aa6b8a37c2932b72fb51f848399ee2dbf94a3c4472c0af22aca2106e90dfe5ca82f2a4bb6a5ac2e52c60f088a604365b5a364ca6",
          "sha256": "00011f49ff02b1787a5537b3f55443122e580cabbd3585961df7501d6685b832",
          "sha1": "6850b128958c6ca5047766ac7d320e40c7500cb6",
          "md5": "db75192a5aec6b9b7c3822155e46fc5d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibjev-jvm-1.0.0.jar",
          "url": "klibjev-jvm-1.0.0.jar",
          "size": 126305,
          "sha512": "a72967427b924d212ce56af8aa6b8a37c2932b72fb51f848399ee2dbf94a3c4472c0af22aca2106e90dfe5ca82f2a4bb6a5ac2e52c60f088a604365b5a364ca6",
          "sha256": "00011f49ff02b1787a5537b3f55443122e580cabbd3585961df7501d6685b832",
          "sha1": "6850b128958c6ca5047766ac7d320e40c7500cb6",
          "md5": "db75192a5aec6b9b7c3822155e46fc5d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibjev-jvm-1.0.0-sources.jar",
          "url": "klibjev-jvm-1.0.0-sources.jar",
          "size": 13336,
          "sha512": "062eebac79b4a9e816858d39efbc0cc034a5f3b0a4981a66a5bb780a5dbaa5cdd245b1e74a6360b2d25c8ca4b9e566923cf2dd95bee049d07f358b8af5b4eaeb",
          "sha256": "8df422d558c814e4e795f5d8b92b6cc78902d66d0a20fd9ee05c50d92076032e",
          "sha1": "fbe5d85148f8fd5f382e016bfb5d60230ac0631c",
          "md5": "d848ceb0e5aeed92b81a7865f70bda9d"
        }
      ]
    }
  ]
}
