{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibjev/1.0.0/klibjev-1.0.0.module",
    "group": "org.jraf.klibjev",
    "module": "klibjev",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibjev-jvm-1.0.0.jar",
          "url": "klibjev-jvm-1.0.0.jar",
          "size": 134184,
          "sha512": "1e4361f7c43359ed525f3188b01237f2502ae3c9179ec7e300f4294c62f06dd0b3f375bc01f9c5a1d5aa476a40b844f16d1632de9f7b0a3ca83ab44faacef20d",
          "sha256": "eddd7b4ca9a7b5ca5520fc1a591c540107ec78ee965d91c5f860ee39c7fad112",
          "sha1": "af57be1a0fc81ccf863b1115c7916226eb13d32e",
          "md5": "0b293d7f769c95f40024d2ead1c14e72"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.drewhamilton.poko",
          "module": "poko-annotations",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibjev-jvm-1.0.0.jar",
          "url": "klibjev-jvm-1.0.0.jar",
          "size": 134184,
          "sha512": "1e4361f7c43359ed525f3188b01237f2502ae3c9179ec7e300f4294c62f06dd0b3f375bc01f9c5a1d5aa476a40b844f16d1632de9f7b0a3ca83ab44faacef20d",
          "sha256": "eddd7b4ca9a7b5ca5520fc1a591c540107ec78ee965d91c5f860ee39c7fad112",
          "sha1": "af57be1a0fc81ccf863b1115c7916226eb13d32e",
          "md5": "0b293d7f769c95f40024d2ead1c14e72"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibjev-jvm-1.0.0-sources.jar",
          "url": "klibjev-jvm-1.0.0-sources.jar",
          "size": 13602,
          "sha512": "d03f5c30bedfe539add9f42ef4d9f1445ecac6d5c55b9c2040758947d88f4e001482592f2c892ed54b76b1b90fcd110e8d39a2315bfcd80f6082221dc7591023",
          "sha256": "ed21512479f5513183c778aa76dfb472f328e929e1ce768ef01c3d31c84b0a64",
          "sha1": "249ce46cb97fd3c0a86d5bae2570d3e5c25c7bde",
          "md5": "4591e562e6362242ee4cce1edaf16865"
        }
      ]
    }
  ]
}
